config/routes.rb
SampleApp::Application.routes.draw do
  root :to => 'staticpages#home'

  resources :users
  match 'signup', to: 'users#new'
  match 'help', to: 'staticpages#help'
  match 'about', to: 'staticpages#about'
  match 'contact', to: 'staticpages#contact'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
	
  def contact
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  		@user = User.find(params[:id])
  end

  def create
  		@user = User.new(params[:user])
  	if @user.save
  		flash[:success] = "Congrats! You have successfully created an Account!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#return the full title on a per-page basis.
	def full_title(page_title)
		base_title = 'Ruby on Rails Tutorial Sample App'
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"

		end
	end	
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	#Returns the Gravatar for the given user.
	def gravatar_for(user)
		gravator_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://gravatar.com/avatar/#{gravator_id}"
		image_tag(gravatar_url, alt: user.name, class:"gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
<a href="http://ajunpreet.freeiz.com/">Rails Test App</a>
by Ajunpreet Bambrah
</small>
<nav>
<ul>
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
		 <%= link_to "My Portfolio", 'http://www.ajunpreet.freeiz.com/', id: "logo", target: "_blank" %>
		 <nav>
		 	<ul class="nav pull-right">
		 		<li><%= link_to "Home", root_path %></li>
		 		<li><%= link_to "Help", help_path %></li>
		 		<li><%= link_to "Sign in", '#' %></li>
		 	</ul>
		 </nav>
			 </div>
		</div>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      This form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <%end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     confirm: "Delete micropost?",
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/staticpages/about.html.erb
<!DOCTYPE html>
<html>
<head>
	<title> <%=  full_title(yield(:title)) %> </title>
	<%= stylesheet_link_tag "application", media: "all" %> 
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-fixed-top">
		<div class="navbar-inner">
		 <%= link_to "sample_app", '#', id: "logo" %>
		 <nav>
		 	<ul class="nav pull-right">
		 		<li><%= link_to "Home", '#' %></li>
		 		<li><%= link_to "Help", '#' %></li>
		 		<li><%= link_to "Sign in", '#' %></li>
		 	</ul>
		 </nav>
		</div>
	</header>
	<div class="container">
	<h1>About us</h1>
	<p>
		This is not being tested but its still there
	</p>
	</div>
</body>
</html>


app/views/staticpages/contact.html.erb
<h1>Contact Us</h1>
<p>Find me in app/views/staticpages/help.html.erb</p>

app/views/staticpages/help.html.erb
<h1>Staticpages#help</h1>
<p>Find me in app/views/staticpages/help.html.erb</p>

app/views/staticpages/home.html.erb
<div class="center hero-unit">
<h1>Welcome to my Rails App</h1>
<p>


</p>

<%= link_to "Sign Up!" , signup_path , class: 'btn btn-large btn-primary'  %>
</div>

<%= link_to image_tag("rails.png", alt: "Ruby on Rails"), 'http://rubyonrails.org/' %>  

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :email %>
	<%= f.text_field :email %>

	<%= f.label :password %>
	<%= f.password_field :password %>

	<%= f.label :password_confirmation, "Confirm Password" %>
	<%= f.password_field :password_confirmation %>


	 <%= f.submit "Create my account", :class => "btn btn-large btn-primary" %>
    <% end %>
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>

<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>

			</h1>
	  	</section>
	</aside>
</div>